/**
 * Mock CodexItem entries for the research view when no campaign data is loaded.
 * Fantasy campaign flavor; ready to replace with API data.
 */
export const MOCK_CODEX_ITEMS = [
  {
    id: "loc-1",
    title: "The Silver Dagger Inn",
    category: "location",
    tags: ["tavern", "safe haven", "gossip"],
    summary: "A worn but welcoming tavern on the edge of the merchant quarter. Known for cheap ale and quieter back rooms.",
    excerpt: "The common room smells of smoke and stew. Regulars nod to newcomers; strangers are watched until they buy a round.",
    content: "The Silver Dagger has stood for forty years. The owner, Marta, keeps a loaded crossbow under the bar. Back rooms host private meetings and the occasional dice game.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-15",
    source: "Campaign notes",
  },
  {
    id: "doc-1",
    title: "The Haunted Mine of Valdris",
    category: "document",
    tags: ["dungeon", "undead", "quest"],
    summary: "Adventure hook: a collapsed mine rumored to hold restless spirits and lost ore.",
    excerpt: "Miners refuse to enter the eastern shaft. Strange lights have been seen at dusk.",
    content: "The mine was sealed after the collapse of '82. Three days ago, a shepherd reported voices from the entrance. Reward offered by the guild for proof of clearing.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-10",
    source: "Adventure outline",
  },
  {
    id: "npc-1",
    title: "Viktor Crane",
    category: "npc",
    tags: ["apothecary", "suspicious", "noir"],
    summary: "Corrupt former guard who runs a back-alley apothecary. Sells information and rare ingredients.",
    excerpt: "Never looks you in the eye. Keeps a ledger he won't show.",
    content: "Viktor Crane, human, mid-40s. Dismissed from the watch after the Mill District fire. Now operates from a cramped shop near the docks. Knows who buys what and when.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-12",
    source: "NPC generator",
  },
  {
    id: "fac-1",
    title: "The Candlekeepers",
    category: "faction",
    tags: ["secret", "religious", "underground"],
    summary: "A secretive sect that worships forgotten gods and collects forbidden texts.",
    excerpt: "They meet in cellars and leave candles at crossroads.",
    content: "The Candlekeepers believe the old gods still listen. They recruit among scholars and the desperate. Their true goals are unknown; their influence reaches into the nobility.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-08",
    source: "Lore",
  },
  {
    id: "lore-1",
    title: "The Fall of the Old Kingdom",
    category: "lore",
    tags: ["history", "empire", "ruins"],
    summary: "Brief history of the kingdom that once ruled this region and why it fell.",
    excerpt: "The capital was abandoned in a single night. No one agrees why.",
    content: "The Old Kingdom stretched from the mountains to the sea. Chronicles speak of a \"silence\" that spread from the throne. The royal line vanished; the cities were left to rot. Only fragments of their language remain.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-05",
    source: "Lore",
  },
  {
    id: "rule-1",
    title: "Travel and Overland Movement",
    category: "rule",
    tags: ["travel", "speed", "random encounters"],
    summary: "Rules for overland travel speed and when to check for encounters.",
    excerpt: "Fast pace: -5 passive Perception. Slow pace: +2 to Survival.",
    content: "Normal pace: 24 miles per day. Fast: 30 miles, -5 to passive Perception. Slow: 18 miles, +2 to Survival. Roll for encounters at dawn and dusk; terrain modifies the roll.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-01",
    source: "Rules reference",
  },
  {
    id: "loc-2",
    title: "Blackwood Crossroads",
    category: "location",
    tags: ["road", "danger", "ambush"],
    summary: "A lonely crossroads where the north road meets the forest track. Notorious for bandits.",
    excerpt: "The gallows here are never empty.",
    content: "Three ways meet: the King's Road north, the forest track to the mines, and the coast path. Patrols are rare. Travelers often find abandoned carts and fresh graves.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-14",
    source: "Campaign notes",
  },
  {
    id: "npc-2",
    title: "Sister Merridy",
    category: "npc",
    tags: ["cleric", "healer", "neutral"],
    summary: "A traveling healer who tends the sick in exchange for stories and spare coin.",
    excerpt: "She asks about your dreams before she tends your wounds.",
    content: "Sister Merridy serves no temple. She walks the roads and stops where she's needed. She is kind but distant; she rarely speaks of her past. Rumored to have once been a soldier.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-11",
    source: "NPC generator",
  },
  {
    id: "doc-2",
    title: "Wanted: The Gray Fox",
    category: "document",
    tags: ["bounty", "criminal", "urban"],
    summary: "Poster describing a notorious thief and the reward for capture.",
    excerpt: "Last seen near the docks. Armed and dangerous.",
    content: "WANTED: The Gray Fox. Theft of noble property, evasion of arrest. Reward: 200 gold crowns. Do not attempt to apprehend alone. Report to the Watch house.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-09",
    source: "Handout",
  },
  {
    id: "rule-2",
    title: "Resting and Hit Dice",
    category: "rule",
    tags: ["rest", "healing", "short rest"],
    summary: "Short and long rest rules; spending hit dice.",
    excerpt: "Short rest: spend hit dice to heal. Long rest: regain all HP and half hit dice.",
    content: "Short rest: at least 1 hour; spend hit dice to regain HP. Long rest: 8 hours; regain all HP, half hit dice (min 1). No more than one long rest per 24 hours.",
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-02",
    source: "Rules reference",
  },
];

/**
 * Mock NPCProfile entries for the NPC Workshop when no campaign NPCs are loaded.
 * Fantasy campaign flavor; ready to replace with API data.
 */
export const MOCK_NPC_PROFILES = [
  {
    id: "mock-npc-1",
    name: "Viktor Crane",
    role: "Suspicious apothecary",
    profession: "Apothecary",
    faction: "Independent",
    location: "Docks district",
    personalityTraits: ["Evasive", "Calculating", "Never looks you in the eye"],
    goals: ["Sell information and rare ingredients", "Stay off the watch's list"],
    secrets: ["Dismissed from the watch after the Mill District fire", "Keeps a ledger he won't show"],
    quirks: ["Taps his fingers when lying", "Always has a bitter smell of herbs"],
    summary: "Corrupt former guard who runs a back-alley apothecary. Sells information and rare ingredients.",
    notes: "Knows who buys what and when. Useful for underworld leads.",
    tags: ["apothecary", "suspicious", "noir", "information broker"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-12",
    disposition: "neutral",
    favorite: true,
  },
  {
    id: "mock-npc-2",
    name: "Marta Thornwood",
    role: "Innkeeper",
    profession: "Innkeeper",
    faction: "Merchant guild",
    location: "The Silver Dagger Inn",
    personalityTraits: ["Cheerful", "Warm", "Watchful"],
    goals: ["Keep the inn profitable", "Protect her regulars"],
    secrets: ["Hidden debt to a local collector", "Keeps a loaded crossbow under the bar"],
    quirks: ["Remembers every face", "Offers stew before asking questions"],
    summary: "Cheerful innkeeper of the Silver Dagger. Welcoming but carries a hidden debt and a crossbow.",
    notes: "Back rooms host private meetings. Good for rumors.",
    tags: ["innkeeper", "tavern", "gossip", "safe haven"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-15",
    disposition: "friendly",
    favorite: true,
  },
  {
    id: "mock-npc-3",
    name: "Captain Aldric Vane",
    role: "Retired mercenary captain",
    profession: "Mercenary (retired)",
    faction: "Veterans' lodge",
    location: "Old garrison quarter",
    personalityTraits: ["Gruff", "Honorable", "Weary"],
    goals: ["Live quietly", "Protect the few he still trusts"],
    secrets: ["Knows who ordered the Mill District fire", "Refuses to speak of it"],
    quirks: ["Stiff leg in cold weather", "Buys a round for strangers who look like soldiers"],
    summary: "Retired mercenary captain with a troubled past. Knows more than he says about the old fire.",
    notes: "Can be hired for tactical advice; won't take the field again.",
    tags: ["mercenary", "veteran", "military", "reluctant ally"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-11",
    disposition: "neutral",
  },
  {
    id: "mock-npc-4",
    name: "Brother Theron",
    role: "Temple scribe",
    profession: "Scribe",
    faction: "Temple of the Dawn",
    location: "Cathedral archives",
    personalityTraits: ["Nervous", "Precise", "Devout"],
    goals: ["Preserve the archives", "Avoid attention"],
    secrets: ["Found a forbidden text; didn't report it", "Afraid of the Candlekeepers"],
    quirks: ["Adjusts his spectacles when lying", "Speaks in whispers in the stacks"],
    summary: "Nervous temple scribe who tends the archives. Knows more about forbidden texts than he admits.",
    notes: "Useful for lore and old documents; easily intimidated.",
    tags: ["scribe", "temple", "lore", "nervous"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-10",
    disposition: "friendly",
  },
  {
    id: "mock-npc-5",
    name: "The Gray Fox",
    role: "Ruthless smuggler",
    profession: "Smuggler",
    faction: "Criminal underworld",
    location: "Docks, moves often",
    personalityTraits: ["Cunning", "Cold", "Charming when useful"],
    goals: ["Stay ahead of the watch", "Control the flow of contraband"],
    secrets: ["Has a safe house in the noble quarter", "Blackmail material on several officials"],
    quirks: ["Always has an exit planned", "Never drinks what he's offered"],
    summary: "Notorious smuggler and thief. Armed and dangerous; reward posted by the watch.",
    notes: "Wanted poster says 200 gold crowns. Last seen near the docks.",
    tags: ["smuggler", "criminal", "wanted", "urban"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-09",
    disposition: "hostile",
  },
  {
    id: "mock-npc-6",
    name: "Sister Merridy",
    role: "Traveling healer",
    profession: "Healer",
    faction: "None",
    location: "Roads",
    personalityTraits: ["Kind", "Distant", "Curious"],
    goals: ["Heal the sick", "Collect stories"],
    secrets: ["Rumored to have once been a soldier", "Serves no temple"],
    quirks: ["Asks about your dreams before tending wounds", "Pays in stories"],
    summary: "A traveling healer who tends the sick in exchange for stories and spare coin.",
    notes: "She is kind but rarely speaks of her past.",
    tags: ["healer", "cleric", "neutral", "traveler"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-11",
    disposition: "friendly",
  },
  {
    id: "mock-npc-7",
    name: "Renn the Silent",
    role: "Mysterious ranger guide",
    profession: "Guide / tracker",
    faction: "None",
    location: "Blackwood and the northern road",
    personalityTraits: ["Quiet", "Observant", "Efficient"],
    goals: ["Lead paying parties safely", "Keep the roads known only to him"],
    secrets: ["Former scout for the army; deserted", "Knows the bandit camps at Blackwood Crossroads"],
    quirks: ["Rarely speaks more than five words", "Leaves a feather at waypoints"],
    summary: "Mysterious ranger who guides travelers through the forest. Knows the roads better than anyone.",
    notes: "Hire for safe passage; don't ask about his past.",
    tags: ["ranger", "guide", "tracker", "forest"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-14",
    disposition: "neutral",
  },
  {
    id: "mock-npc-8",
    name: "Lady Cressida Vale",
    role: "Noble patron",
    profession: "Noble",
    faction: "Court",
    location: "Noble quarter",
    personalityTraits: ["Refined", "Calculating", "Generous to useful people"],
    goals: ["Expand influence", "Find leverage over rivals"],
    secrets: ["Secretly funds the Candlekeepers", "Uses the Gray Fox for certain errands"],
    quirks: ["Never sits with her back to the door", "Remembers every favor"],
    summary: "Wealthy noble who patronizes artists and adventurers. Has hidden ties to the Candlekeepers.",
    notes: "Good for funding; she expects favors in return.",
    tags: ["noble", "patron", "court", "secretive"],
    campaign: "Shadows of the Old Road",
    updatedAt: "2024-01-08",
    disposition: "neutral",
  },
];

/**
 * Mock voice profiles for Voice Studio when backend is not ready.
 */
export const MOCK_VOICE_PROFILES = [
  {
    id: "voice-1",
    voice_id: "voice-1",
    name: "Gravelly Mercenary",
    source: "system",
    status: "ready",
    accent: "Common",
    tone: "rough",
    tags: ["combat", "soldier", "gruff"],
    sampleUrl: undefined,
    assignedNPCs: [],
    description: "Deep, battle-worn voice for soldiers and sellswords.",
    updatedAt: "2024-01-15",
  },
  {
    id: "voice-2",
    voice_id: "voice-2",
    name: "Warm Tavernkeeper",
    source: "system",
    status: "ready",
    accent: "Rural",
    tone: "warm",
    tags: ["tavern", "friendly", "innkeeper"],
    assignedNPCs: ["mock-npc-1"],
    description: "Welcoming and hearty, perfect for innkeepers and merchants.",
    updatedAt: "2024-01-14",
  },
  {
    id: "voice-3",
    voice_id: "voice-3",
    name: "Noble Elven Scholar",
    source: "cloned",
    status: "ready",
    accent: "Elvish",
    tone: "noble",
    tags: ["elf", "scholar", "formal"],
    assignedNPCs: [],
    description: "Refined, measured elven voice for sages and nobles.",
    updatedAt: "2024-01-13",
  },
  {
    id: "voice-4",
    voice_id: "voice-4",
    name: "Eerie Whispering Oracle",
    source: "cloned",
    status: "ready",
    accent: "Unknown",
    tone: "mysterious",
    tags: ["oracle", "prophet", "whisper"],
    assignedNPCs: [],
    description: "Haunting whisper for seers and cryptic NPCs.",
    updatedAt: "2024-01-12",
  },
  {
    id: "voice-5",
    voice_id: "voice-5",
    name: "Rough Smuggler Captain",
    source: "custom",
    status: "ready",
    accent: "Coastal",
    tone: "rough",
    tags: ["smuggler", "pirate", "sly"],
    assignedNPCs: [],
    description: "Gritty, sly voice for rogues and seafarers.",
    updatedAt: "2024-01-11",
  },
  {
    id: "voice-6",
    voice_id: "voice-6",
    name: "Calm Narrator",
    source: "system",
    status: "ready",
    accent: "Neutral",
    tone: "neutral",
    tags: ["narration", "gm", "neutral"],
    assignedNPCs: [],
    description: "Clear, neutral narrator for scene readouts and descriptions.",
    updatedAt: "2024-01-10",
  },
  {
    id: "voice-7",
    voice_id: "voice-7",
    name: "Grim Executioner",
    source: "system",
    status: "ready",
    accent: "Common",
    tone: "grim",
    tags: ["villain", "dark", "authority"],
    assignedNPCs: [],
    description: "Cold, authoritative voice for antagonists and authority figures.",
    updatedAt: "2024-01-09",
  },
  {
    id: "voice-8",
    voice_id: "voice-8",
    name: "Mysterious Hooded Stranger",
    source: "cloned",
    status: "training",
    accent: "Muted",
    tone: "mysterious",
    tags: ["mystery", "stranger"],
    assignedNPCs: [],
    description: "Cloned voice currently in training.",
    updatedAt: "2024-01-08",
  },
];

/**
 * Mock generated audio clips for Voice Studio.
 */
export const MOCK_GENERATED_AUDIO = [
  {
    id: "gen-1",
    title: "Silver Dagger intro",
    voiceId: "voice-2",
    duration: "0:12",
    createdAt: "2024-01-15T14:30:00Z",
    campaign: "Shadows of the Old Road",
    type: "narration",
  },
  {
    id: "gen-2",
    title: "Viktor Crane dialogue",
    voiceId: "voice-5",
    duration: "0:08",
    createdAt: "2024-01-15T12:00:00Z",
    campaign: "Shadows of the Old Road",
    type: "npc-dialogue",
  },
  {
    id: "gen-3",
    title: "Haunted Mine readout",
    voiceId: "voice-6",
    duration: "0:45",
    createdAt: "2024-01-14T18:00:00Z",
    campaign: "Shadows of the Old Road",
    type: "scene-readout",
  },
  {
    id: "gen-4",
    title: "Oracle prophecy",
    voiceId: "voice-4",
    duration: "0:22",
    createdAt: "2024-01-14T10:00:00Z",
    campaign: "Shadows of the Old Road",
    type: "npc-dialogue",
  },
  {
    id: "gen-5",
    title: "Tavern ambience line",
    voiceId: "voice-2",
    duration: "0:05",
    createdAt: "2024-01-13T20:00:00Z",
    campaign: "Shadows of the Old Road",
    type: "narration",
  },
  {
    id: "gen-6",
    title: "Elven scholar greeting",
    voiceId: "voice-3",
    duration: "0:15",
    createdAt: "2024-01-13T15:00:00Z",
    campaign: "Shadows of the Old Road",
    type: "npc-dialogue",
  },
];

/**
 * Example training job for clone wizard.
 */
export const MOCK_VOICE_CLONE_JOB = {
  id: "job-mock-1",
  status: "processing",
  progress: 65,
  stepLabel: "Training model…",
};
